/*
## Search
*/
/*
### API
*/
# @name Search endpoint is enabled
# @ERROR
GET /__api/search

?? status == 200
?? header content-type startsWith text/plain
###
# @name Search endpoint without autoindex is disabled
GET {{without_autoindex}}/__api/search

?? status == 404
