name: Verify that docker image builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: bouyguestelecom/a7:snapshot
          platforms: linux/amd64,linux/arm64
