name: Verify that docker image builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image with tag snapshot
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bouyguestelecom/a7:snapshot
          platforms: linux/amd64,linux/arm64
      - name: Setup services for testing purpose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./test/integration/compose.yml"
        env:
          CUSTOM_VARIABLE: "test"
      - name: Start docker compose
        run: cd ./test/integration && docker compose up -d
      - name: Run tests against services
        run: cd ./test/integration && ./run.sh
      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: http-yac-test-results
          path: ./test/integration/test-output.json
          if-no-files-found: error
        if: ${{ always() }}
