name: Run Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build and push docker image with tag snapshot
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: localhost:5000/a7:latest
          platforms: linux/amd64
      - name: Setup services for testing purpose
        run: cd ./test/integration && docker compose up -d -e IMAGE_TAG=localhost:5000/test/a7:latest
      - name: Run tests against services
        run: cd ./test/integration && ./run.sh
      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: http-yac-test-results
          path: ./test/integration/test-output.json
          if-no-files-found: error
        if: ${{ always() }}
